# Site settings
title: Matt Morgan
email: matt@mattmrgn.com
description: > # this means to ignore newlines until "baseurl:"
  Things about Matt Morgan
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://mattmrgn.com" # the base hostname & protocol for your site
twitter_username: mattmrgn

# Build settings
markdown: kramdown
